Feat:landing page
Cali-Finance/cali-app pull request #1
Opened 2022-08-09 12:33 UTC by Pedrobourguignon

- [x] Create Cali Landing Page

2022-08-09 13:49 UTC, ThalesBMC requested changes

2022-08-09 13:49 UTC, ThalesBMC commented on components/Button/PrimaryButton.tsx
> +		<Flex boxShadow="0px 0px 10px rgba(232, 49, 81, 0.5)" mt="16">
Please put the boxShadow in chakra theme

2022-08-09 13:49 UTC, ThalesBMC commented on components/Header/Header.tsx
> +								</MenuItem>
Transform  this in a component but put inside this file and do not create other file for it.
So you can call it with  arrayOfNames.map 
```
<MenuItem>
							<NextLink href="/">
								<Link>Docs</Link>
				</NextLink>
</MenuItem>
```

2022-08-09 13:49 UTC, ThalesBMC commented on components/Header/Header.tsx
> +				</NextLink>
Transform this in a component but put inside this file and do not create other file for it.
So you can call it with arrayOfNames.map

2022-08-09 13:49 UTC, ThalesBMC commented on layouts/Background/Background.tsx
> +			background="linear-gradient(112.87deg, rgba(26, 29, 225, 0.1) 0%, rgba(16, 15, 18, 0.1) 32.29%, rgba(16, 15, 18, 0.1) 66.15%, rgba(2, 228, 209, 0.1) 100%);"
put this on a chakra variable

2022-08-09 13:49 UTC, ThalesBMC commented on pages/index.tsx
> +						.”
If you are using this “ “ please put inside a text

2022-08-10 12:54 UTC, ThalesBMC approved these changes

2022-08-11 12:01 UTC, amaurymagalhaes requested changes

2022-08-11 12:01 UTC, amaurymagalhaes commented on pages/index.tsx
> +import { Background } from 'layouts/Background/Background'
This should be imported from a barrel like  
```ts
import { Background } from 'layouts'
```

2022-08-12 13:06 UTC, merged